ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.servicewiz.in
CATALOGUE_HOST: catalogue-dev.servicewiz.in
REDIS_HOST: redis-dev.servicewiz.in
USER_HOST: user-dev.servicewiz.in
CART_HOST: cart-dev.servicewiz.in
MYSQL_HOST: mysql-dev.servicewiz.in
SHIPPING_HOST: shipping-dev.servicewiz.in
RABBITMQ_HOST: rabbitmq-dev.servicewiz.in
PAYMENT_HOST: payment-dev.servicewiz.in