---
# 1. BASE SETUP: User, directory, and code download
- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

# 2. RUNTIME SETUP: Maven build process
- name: java setup
  ansible.builtin.import_role:
    name: common
    tasks_from: java-setup.yaml

# 3. DB MIGRATION: Loading schema into MySQL
- name: install mysql python dependencies
  ansible.builtin.pip:
    name: 
      - cryptography
      - PyMySQL
    executable: pip3

- name: import shipping data
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: "{{ MYSQL_HOST }}"
    login_user: root
    login_password: "{{ MYSQL_ROOT_PASSWORD }}" # Using the variable we defined!
    target: "{{ item }}"
  loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql

# 4. SERVICE CONFIG: Background process setup
- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml

# 5. ACTIVATION
- name: start shipping
  ansible.builtin.service:
    name: shipping
    state: restarted
    enabled: yes